name: Deployment
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: yarn install
      - name: Build documentation
        run: yarn build
      - name: Deploy documentation
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/dist
          commit_message: ${{ github.event.head_commit.message }}
          cname: discordeno.js.org
          keep_files: true
