name: Test
on: 
  push:
    branches:
      - stable
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@master
      - name: Cache dependencies
        run: deno cache mod.ts
      - name: Run test script
        run: deno test -A
    env:
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}